### ISSUE TITLE
Mention "CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y" in "Bluetooth#Troubleshooting"

### ISSUE THREAD

**Issue by dennisorlando** [zmkfirmware/zmk#2170]
Hi, I just fixed a bluetooth connectivity issue by following instructions in #1487 
Updating the documentation with the fixes described in the issue might be worth it, although I don't actually know what `CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y` does and the reason why I can't connect to my split keyboard without it.

**Comment by slabua** [comment]
Wait for it. A lot of people who have done the same in that thread are again encountering the same connection issues.

**Comment by caksoylar** [comment]
My impression is that Zephyr 3.5 upgrade helped a lot with issues, but this setting (which only disables PHY 2M at the moment) might still be necessary for some people (and it no longer seems to hurt with some Macs). We need more data points after the upgrade, then we can see if we should recommend it in troubleshooting or perhaps default to it.

**Comment by caksoylar** [comment]
Fixed by #2387.

**Comment by slabua** [comment]
Updating the documentation does not fix the problem, though.

**Comment by caksoylar** [comment]
> Updating the documentation does not fix the problem, though.

This Github issue is specifically about missing documentation about the Kconfig symbol, so not sure what the complaint is about.
